language: node_js
node_js: stable
addons:
  firefox: '46.0'
  sauce_connect: true
before_script:
  - npm install -g bower web-component-tester
  - bower install
script:
  - xvfb-run wct
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
sudo: required
notifications:
  email: maslov.dmitrij@gmail.com
