language: node_js
node_js: stable
before_script:
  - npm install -g bower web-component-tester
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - wct
notifications:
  email: maslov.dmitrij@gmail.com
